# Generated by Django 3.2.5 on 2022-02-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=1000)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_datetime', models.DateTimeField()),
                ('historical', models.TextField()),
            ],
        ),
    ]
