# Generated by Django 3.2.5 on 2022-02-24 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bal_hist', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Holdings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=10)),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.stockdata')),
            ],
        ),
    ]
