# Generated by Django 3.2.5 on 2022-02-24 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_holdings_portfolio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Holdings',
            new_name='Holding',
        ),
    ]
