# Generated by Django 3.2.5 on 2022-02-24 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_rename_holdings_holding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holding',
            name='id',
        ),
        migrations.AddField(
            model_name='holding',
            name='owner',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='auth.user'),
            preserve_default=False,
        ),
    ]
