# Generated by Django 3.2.5 on 2022-02-24 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.DecimalField(decimal_places=4, max_digits=10)),
                ('time', models.DateTimeField()),
                ('portfolio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.portfolio')),
                ('stock_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='main.stockdata')),
            ],
        ),
    ]
