# Generated by Django 3.2.5 on 2022-02-24 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_transactions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockData',
            new_name='Stock',
        ),
        migrations.RenameModel(
            old_name='Transactions',
            new_name='Transaction',
        ),
    ]
