# Generated by Django 3.2.5 on 2022-03-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_stock_display_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='buy',
            field=models.BooleanField(default=True),
        ),
    ]
