# Generated by Django 3.2.9 on 2022-03-21 15:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0013_alter_profile_friends_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='requested_me',
            field=models.ManyToManyField(blank=True, default=None, related_name='received_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='requested_friends',
            field=models.ManyToManyField(blank=True, default=None, related_name='sent_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
