# Generated by Django 3.2.9 on 2022-03-21 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20220321_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='requested_friends',
        ),
    ]
