# Generated by Django 3.2.5 on 2022-03-23 00:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_league_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
