# Generated by Django 3.2.5 on 2022-03-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_league_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='day_change',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='stock',
            name='week_change',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
