# Generated by Django 3.2.12 on 2022-03-24 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20220324_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leagueportfolio',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='rank',
        ),
    ]
