# Generated by Django 3.1.1 on 2022-03-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20220324_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagueportfolio',
            name='rank',
            field=models.IntegerField(default=999),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='rank',
            field=models.IntegerField(default=999),
        ),
    ]
