# Generated by Django 3.2.5 on 2022-03-28 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20220325_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='rank',
            new_name='leaderboard_ranking',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='desc',
            new_name='description',
        ),
    ]
